#!/usr/bin/env python
# -*- python -*-
from __future__ import print_function
import os, sys, re
import MySQLdb as mdb

def main():
  try:
    con = mdb.connect("localhost", 'testuser','test623', 'HPCTips')
    cur = con.cursor()
    cur.execute("select version()")
    ver = cur.fetchone()

    print("Database version : %s " % ver)
  except mdb.Error, e:
    print("Error %d: %s" % (e.args[0], e.args[1]))
    sys.exit(-1)

  finally:
    if (con):
      con.close()
      

if ( __name__ == '__main__'): main()
